spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

file:
  dir: ${file-dir}

logging:
  level:
    org.hibernate.SQL: debug

